### ISSUE TITLE
matFromRollPitchYaw name does not match parameter order

### ISSUE THREAD

**Issue by Pyrolistical** [zig-gamedev/zig-gamedev#640]
The `fn` name is in the order of `roll, pitch, yaw`, but the parameter order is `pitch, yaw, roll`.
This is especially confusing for the vector versions.

Affected fns:
```zig
fn matFromRollPitchYaw(pitch: f32, yaw: f32, roll: f32) Mat;
fn matFromRollPitchYawV(angles: Vec) Mat;
fn quatFromRollPitchYaw(pitch: f32, yaw: f32, roll: f32) Quat;
fn quatFromRollPitchYawV(angles: Vec) Quat;
```

**Comment by hazeycode** [comment]
Since `quatFromRollPitchYawV` requires `| pitch | yaw | roll | 0 |` I think we should rename these fns.

**Comment by michal-z** [comment]
This is by design. The name describes the order of rotations (the order in which matrices are multiplied). The order of parameters is x (pitch), y (yaw), z (roll).

This is the convention borrowed from DirectX Math. I don't think we should change it.

**Comment by Srekel** [comment]
IMHO it makes sense that the name matches the order they are applied, but I'm not sure why it makes sense to pass them in in order of x,y,z, since that's not typically names you use anyway in this context. That is, even if I had my euler angle as a vec3, I would still first make the mental conversion of x=pitch and assume it should go as the second parameter. 

Granted, there is some value to adhering to DX but I bumped into this and I haven't used the DX math library as I would assume is true of most people. But, if there was a comment about it then it would be easier to note the difference.

An alternative would be to take a `struct {pitch, yaw, roll}` as then it would be impossible to make the mistake, and if it was union'd with a `[3]f32` you could pass that in in the (likely?) offchance that's how you're storing your euler angle.

**Comment by michal-z** [comment]
Please remember that we also have version that takes vector as a parameter:

`fn matFromRollPitchYawV(angles: Vec) Mat;`

This is for speed to keep everything in CPU registers. It would be very confusing to mess with ordering here.

**Comment by hazeycode** [comment]
What if we rename these fns to `matFromAngles, `matFromAnglesV`, `quatFromAngles, `quatFromAnglesV` and annotate the vector versions with doc-comments to describe the layout? (for the scalar versions the argument name is sufficient documentation)
